### ISSUE TITLE
Generate one-page navigable documentation alternative

### ISSUE THREAD

**Issue by skiadas** [PanthR/panthrdoc#17]

**Comment by bwahl** [comment]
Do you mean, the documentation would be in a single .html file?  With links to make it navigable?

If we posted the .html file to the OneDrive folders for our FEC reviews, FEC members could just open it in their browsers, right?  Or do we need to put it up on vault?

**Comment by skiadas** [comment]
Right, it would be fully self-contained. But it would require a fair bit of recoding, I don't think it's a fast fix. Hm maybe it might be easy, I'll ponder on it.
